version: 2
jobs:
    build:
        working_directory: ~/project
        docker:
            - image: circleci/node:8.9.3-browsers
        steps:
            - checkout

workflows:
  version: 2

  build:
    jobs:
      - build:
          branches:
            ignore:
              - gh-pages
