version: 2
jobs:
    build:
        working_directory: ~/project
        docker:
            - image: circleci/node:chakracore-8.11-browsers-legacy
        steps:
            - checkout
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            - run:
                name: Show current directory
                command: pwd
            - run:
                name: environment variables
                command: npm run environment-variables
            # - restore_cache:
            #     keys:
            #         - v1-dependencies-{{ checksum "package.json" }}
            - run:
                name: Rebuild Node Sass
                command: npm run frontend-rebuild-node-sass
            - run:
                name: Install dependencies
                command: npm run frontend-install
            # - run:
            #     name: Node Sass
            #     command: npm run frontend-install-node-sass
            # - run:
            #     name: Rebuild Node Sass
            #     command: npm run frontend-rebuild-node-sass
            - save_cache:
                key: v1-dependencies-{{ checksum "package.json" }}
                paths:
                    - node_modules
            - run:
                name: Linting
                command: npm run frontend-lint
            - run:
                name: Node Sass
                command: npm run frontend-install-node-sass
            - run:
                name: Testing
                command: npm run frontend-test
            - run:
                name: Building
                command: npm run frontend-build
            - save_cache:
                key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
                paths:
                    - frontend/dist
                    - frontend/package.json
                    - package.json
                    - firebase.json
                    - .firebaserc
                    - functions
    deploy:
        docker:
            - image: circleci/node:chakracore-8.11-browsers-legacy
        working_directory: ~/project
        steps:
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            - restore_cache:
                key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
            - run:
                name: Install Firebase
                command: npm install --save-dev firebase-tools
            - run:
                name: Deploy Master to Firebase
                command: npm run frontend-deploy
            - run:
                name: Deploy Cloud Functions to Firebase
                command: npm run functions-deploy

workflows:
    version: 2
    -deploy:
        jobs:
        - build
        - deploy:
            requires:
                - build
            filters:
                branches:
                    only: master