version: 2
jobs:
    build:
        working_directory: ~/project
        docker:
            - image: circleci/node:8.9.3-browsers
        steps:
            - checkout
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            - run:
                name: Show current directory
                command: pwd
            - run:
                name: environment variables
                command: npm run environment-variables
            - run:
                name: environment file
                command: curl -H "Authorization:token $GITHUB_TOKEN" -H "Accept:application/vnd.github.v3.raw" -O -L $OC_ENVIRONMENT
            - run:
                name: environment prod file
                command: curl -H "Authorization:token $GITHUB_TOKEN" -H "Accept:application/vnd.github.v3.raw" -O -L $OC_ENVIRONMENT_PROD
            - run:
                name: cypress json file
                command: curl -H "Authorization:token $GITHUB_TOKEN" -H "Accept:application/vnd.github.v3.raw" -O -L $OC_CYPRESS_JSON
            - run:
                name: delete old environment file
                command: rm -rf frontend/src/environments/environment.ts
            - run:
                name: delete old enviornment file
                command: rm -rf frontend/src/environments/environment.prod.ts
            - run:
                name: delete old enviornment file
                command: rm -rf frontend/cypress.json
            - run:
                name: copy new files
                command: cp environment.ts frontend/src/environments/environment.ts
            - run:
                name: copy new files
                command: cp environment.prod.ts frontend/src/environments/environment.prod.ts
            - run:
                name: copy new files
                command: cp cypress.json frontend/cypress.json            
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
            - run:
                name: Install dependencies
                command: npm run frontend-install
            - run:
                name: Cypress Install
                command: npm run frontend-cypress-install
            - save_cache:
                key: v1-dependencies-{{ checksum "package.json" }}
                paths:
                    - frontend/node_modules
                    - /home/circleci/.cache/Cypress
            - run:
                name: Linting
                command: npm run frontend-lint
            - run:
                name: Testing
                command: npm run frontend-test
            # - run:
            #     name: e2e Testing
            #     command: npm run frontend-cypress-run
            - run:
                name: Building
                command: npm run frontend-build
            - save_cache:
                key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
                paths:
                    - frontend
                    - functions
                    - package.json
                    - .firebaserc
                    - firebase.json

    deploy:
        docker:
            - image: circleci/node:8.9.3-browsers
        working_directory: ~/project
        steps:
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            - restore_cache:
                key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
            - run:
                name: Install Firebase
                command: npm install --save-dev firebase-tools
            - run:
                name: Functions Install
                command: npm run functions-install
            - run:
                name: Deploy Master to Firebase
                command: npm run prod-deploy

workflows:
    version: 2
    -deploy:
        jobs:
        - build
        - deploy:
            requires:
                - build
            filters:
                branches:
                    only: master