version: 2
jobs:
    build:
        working_directory: ~/project
        docker:
            - image: circleci/node:8.9.3-browsers
        steps:
            - checkout
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            - run:
                name: Show current directory
                command: pwd
            - run:
                name: environment variables
                command: npm run environment-variables
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
            - run:
                name: Rebuild Node Sass
                command: npm run frontend-rebuild-node-sass
            - run:
                name: Install dependencies
                command: npm run frontend-install
            - save_cache:
                key: v1-dependencies-{{ checksum "package.json" }}
                paths:
                    - frontend/node_modules
            - run:
                name: Linting
                command: npm run frontend-lint
            - run:
                name: Node Sass
                command: npm run frontend-install-node-sass
            - run:
                name: Testing
                command: npm run frontend-test
            - run:
                name: Building
                command: npm run frontend-build
            - save_cache:
                key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
                paths:
                    - frontend
                    - functions
                    - package.json
                    - .firebaserc
                    - firebase.json

    deploy:
        docker:
            - image: circleci/node:8.9.3-browsers
        working_directory: ~/project
        steps:
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            - restore_cache:
                key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
            - run:
                name: Install Firebase
                command: npm install --save-dev firebase-tools
            - run:
                name: Functions Install
                command: npm run functions-install
            - run:
                name: Deploy Master to Firebase
                command: npm run prod-deploy
            - run:
                name: install MkDocs
                command: pip install mkdocs
            - run:
                name: build MkDocs user guide
                command: npm run docs-build
            - run:
                name: deploy MkDocs user guide
                command: npm run docs-deploy

workflows:
    version: 2
    -deploy:
        jobs:
        - build
        - deploy:
            requires:
                - build
            filters:
                branches:
                    only: master